# Generated by Django 5.2.7 on 2025-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default='M', max_length=1),
        ),
    ]
