# Generated by Django 5.2.7 on 2025-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='goals',
            field=models.ManyToManyField(to='main_app.goal'),
        ),
    ]
