# Generated by Django 5.2.7 on 2025-11-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_visionboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-status']},
        ),
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateField(),
        ),
    ]
