# Generated by Django 5.2.7 on 2025-11-04 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_task_options_alter_emotion_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_report', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_checked_in', models.DateTimeField(auto_now=True)),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
