# Generated by Django 5.2.7 on 2025-11-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_aianalysisreport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
