# Generated by Django 5.2.7 on 2025-11-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_emotion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
